/*
 * SonarQube Java
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.java.checks.helpers;

import org.sonar.java.model.ExpressionUtils;
import org.sonar.plugins.java.api.semantic.Type;
import org.sonar.plugins.java.api.tree.AnnotationTree;
import org.sonar.plugins.java.api.tree.ExpressionTree;
import org.sonar.plugins.java.api.tree.LiteralTree;
import org.sonar.plugins.java.api.tree.Tree;

/**
 * Recognizes strings that are most likely not hand-written and maintained by developers.
 *
 * Currently we ignore:
 *
 * <ul>
 *   <li>{@code d1} strings in {@code kotlin.Metadata} annotations</li>
 *   <li>All strings in {@code kotlin.jvm.internal.SourceDebugExtension} annotations</li>
 *   <li>All strings in {@code kotlin.coroutines.jvm.internal.DebugMetadata} annotations</li>
 * </ul>
 */
public final class GeneratedStringLiteralRecognizer {

  private static final String KOTLIN_METADATA = "kotlin.Metadata";
  private static final String KOTLIN_SOURCE_DEBUG_EXTENSION = "kotlin.jvm.internal.SourceDebugExtension";
  private static final String KOTLIN_DEBUG_METADATA = "kotlin.coroutines.jvm.internal.DebugMetadata";

  private GeneratedStringLiteralRecognizer() {
  }

  /**
   * Checks whether a string or text block literal is (most likely) generated by a known tool.
   * and not hand-written by developers. Useful for rule suppression for rules that raise on such literals.
   *
   * @param literal the literal to check
   * @return {@code true} when the literal is recognized as generated
   */
  public static boolean isGenerated(LiteralTree literal) {
    if (!literal.is(Tree.Kind.STRING_LITERAL, Tree.Kind.TEXT_BLOCK)) {
      return false;
    }

    Tree annotationArgument = literal;
    while (annotationArgument.parent() != null && !annotationArgument.parent().is(Tree.Kind.ARGUMENTS)) {
      annotationArgument = annotationArgument.parent();
    }

    Tree arguments = annotationArgument.parent();
    if (arguments == null || !(arguments.parent() instanceof AnnotationTree annotation)) {
      return false;
    }

    return isAnnotationType(annotation, KOTLIN_SOURCE_DEBUG_EXTENSION)
      || isAnnotationType(annotation, KOTLIN_DEBUG_METADATA)
      || (annotationArgument instanceof ExpressionTree argument
        && "d1".equals(ExpressionUtils.annotationAttributeName(argument))
        && isAnnotationType(annotation, KOTLIN_METADATA));
  }

  private static boolean isAnnotationType(AnnotationTree annotation, String fullyQualifiedName) {
    Type annotationType = annotation.symbolType();
    String unqualifiedName = fullyQualifiedName.substring(fullyQualifiedName.lastIndexOf('.') + 1);
    return annotationType.is(fullyQualifiedName)
      || (annotationType.isUnknown() && annotationType.name().equals(unqualifiedName));
  }

}
