# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - semantic

SQ_VERSION:
  - DEV
  - LATEST_RELEASE[6.7]

exclude:
#exclude plugin tests on windows slaves
  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: DEV
  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]
#exclude all ruling jobs other than on LATEST_RELEASE[6.7] on linux
  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: DEV
#exclude all ruling jobs other than on LATEST_RELEASE[6.7] on windows
  - TEST: ruling
    SLAVE: windows
    SQ_VERSION: DEV
#eclude all semantic jobs on linux slaves other than LATEST_RELEASE[6.7]
  - TEST: semantic
    SLAVE: linux
    SQ_VERSION: DEV
#eclude all semantic jobs on windows slaves
  - TEST: semantic
    SLAVE: windows
    SQ_VERSION: DEV
  - TEST: semantic
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]
