# Override license defined in parent POM
# See check-license-compatibility.sh

org.ow2.asm--asm--8.0.1=bsd
org.ow2.asm--asm-analysis--8.0.1=bsd
org.ow2.asm--asm-commons--8.0.1=bsd
org.ow2.asm--asm-tree--8.0.1=bsd
org.ow2.asm--asm-util--8.0.1=bsd

# Tomcat uses both Apache v2 and CDDL, but its POM combines them in a way the license plugin cannot recognize.
# Override to the accepted Apache license, as previously done for older versions of this artifact.
org.apache.tomcat--tomcat-servlet-api--9.0.120=apache_v2
