/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.myapp;

import java.util.ArrayList;
import java.util.List;

public class App {

    List<int[]> arrayList = new ArrayList<>();

    public String getGreeting(int[] arr) {
        arrayList.contains(arr);
        return "";
    }
}
