/*
 * SonarQube Java
 * Copyright (C) 2012-2017 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.java.checks;

import org.sonar.java.checks.naming.BadAbstractClassNameCheck;
import org.sonar.java.checks.naming.BadClassNameCheck;
import org.sonar.java.checks.naming.BadConstantNameCheck;
import org.sonar.java.checks.naming.BadFieldNameCheck;
import org.sonar.java.checks.naming.BadFieldNameStaticNonFinalCheck;
import org.sonar.java.checks.naming.BadInterfaceNameCheck;
import org.sonar.java.checks.naming.BadLocalVariableNameCheck;
import org.sonar.java.checks.naming.BadMethodNameCheck;
import org.sonar.java.checks.naming.BadPackageNameCheck;
import org.sonar.java.checks.naming.BadTestClassNameCheck;
import org.sonar.java.checks.naming.BadTestMethodNameCheck;
import org.sonar.java.checks.naming.BadTypeParameterNameCheck;
import org.sonar.java.checks.naming.BooleanMethodNameCheck;
import org.sonar.java.checks.naming.ClassNamedLikeExceptionCheck;
import org.sonar.java.checks.naming.FieldNameMatchingTypeNameCheck;
import org.sonar.java.checks.naming.KeywordAsIdentifierCheck;
import org.sonar.java.checks.naming.MethodNameSameAsClassCheck;
import org.sonar.java.checks.naming.MethodNamedEqualsCheck;
import org.sonar.java.checks.naming.MethodNamedHashcodeOrEqualCheck;
import org.sonar.java.checks.serialization.CustomSerializationMethodCheck;
import org.sonar.java.checks.serialization.ExternalizableClassConstructorCheck;
import org.sonar.java.checks.serialization.PrivateReadResolveCheck;
import org.sonar.java.checks.serialization.SerialVersionUidCheck;
import org.sonar.java.checks.serialization.SerializableComparatorCheck;
import org.sonar.java.checks.serialization.SerializableFieldInSerializableClassCheck;
import org.sonar.java.checks.serialization.SerializableObjectInSessionCheck;
import org.sonar.java.checks.serialization.SerializableSuperConstructorCheck;
import org.sonar.java.checks.synchronization.DoubleCheckedLockingCheck;
import org.sonar.java.checks.synchronization.SynchronizationOnGetClassCheck;
import org.sonar.java.checks.synchronization.TwoLocksWaitCheck;
import org.sonar.java.checks.synchronization.WriteObjectTheOnlySynchronizedMethodCheck;
import org.sonar.java.checks.unused.UnusedLabelCheck;
import org.sonar.java.checks.unused.UnusedLocalVariableCheck;
import org.sonar.java.checks.unused.UnusedMethodParameterCheck;
import org.sonar.java.checks.unused.UnusedPrivateFieldCheck;
import org.sonar.java.checks.unused.UnusedPrivateMethodCheck;
import org.sonar.java.checks.unused.UnusedReturnedDataCheck;
import org.sonar.java.checks.unused.UnusedTestRuleCheck;
import org.sonar.java.checks.unused.UnusedTypeParameterCheck;
import org.sonar.java.checks.xml.ejb.DefaultInterceptorsLocationCheck;
import org.sonar.java.checks.xml.ejb.InterceptorExclusionsCheck;
import org.sonar.java.checks.xml.maven.ArtifactIdNamingConventionCheck;
import org.sonar.java.checks.xml.maven.DependencyWithSystemScopeCheck;
import org.sonar.java.checks.xml.maven.DeprecatedPomPropertiesCheck;
import org.sonar.java.checks.xml.maven.DisallowedDependenciesCheck;
import org.sonar.java.checks.xml.maven.GroupIdNamingConventionCheck;
import org.sonar.java.checks.xml.maven.PomElementOrderCheck;
import org.sonar.java.checks.xml.spring.SingleConnectionFactoryCheck;
import org.sonar.java.checks.xml.struts.ActionNumberCheck;
import org.sonar.java.checks.xml.struts.FormNameDuplicationCheck;
import org.sonar.java.checks.xml.web.SecurityConstraintsInWebXmlCheck;
import org.sonar.java.checks.xml.web.ValidationFiltersCheck;
import org.sonar.java.se.checks.ConditionAlwaysTrueOrFalseCheck;
import org.sonar.java.se.checks.CustomUnclosedResourcesCheck;
import org.sonar.java.se.checks.DivisionByZeroCheck;
import org.sonar.java.se.checks.LocksNotUnlockedCheck;
import org.sonar.java.se.checks.NoWayOutLoopCheck;
import org.sonar.java.se.checks.NonNullSetToNullCheck;
import org.sonar.java.se.checks.NullDereferenceCheck;
import org.sonar.java.se.checks.OptionalGetBeforeIsPresentCheck;
import org.sonar.java.se.checks.UnclosedResourcesCheck;
import org.sonar.plugins.java.api.JavaCheck;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class CheckList {

  public static final String REPOSITORY_KEY = "squid";

  private CheckList() {
  }

  public static List<Class> getChecks() {
    List<Class> builder = new ArrayList<>();
    builder.addAll(getJavaChecks());
    builder.addAll(getJavaTestChecks());
    builder.addAll(getXmlChecks());
    return Collections.unmodifiableList(builder);
  }

  public static List<Class<? extends JavaCheck>> getJavaChecks() {
    List<Class<? extends JavaCheck>> builder = new ArrayList<>();
    builder.add(TabCharacterCheck.class);
    builder.add(TooLongLineCheck.class);
    builder.add(MissingNewLineAtEndOfFileCheck.class);
    builder.add(VarArgCheck.class);
    builder.add(ParsingErrorCheck.class);
    builder.add(MethodComplexityCheck.class);
    builder.add(ClassComplexityCheck.class);
    builder.add(UndocumentedApiCheck.class);
    builder.add(NoSonarCheck.class);
    builder.add(CommentedOutCodeLineCheck.class);
    builder.add(EmptyFileCheck.class);
    builder.add(EmptyBlockCheck.class);
    builder.add(TooManyLinesOfCodeInFileCheck.class);
    builder.add(TooManyParametersCheck.class);
    builder.add(RawExceptionCheck.class);
    builder.add(BadMethodNameCheck.class);
    builder.add(BadClassNameCheck.class);
    builder.add(BadInterfaceNameCheck.class);
    builder.add(BadConstantNameCheck.class);
    builder.add(BadFieldNameCheck.class);
    builder.add(BadFieldNameStaticNonFinalCheck.class);
    builder.add(BadLocalVariableNameCheck.class);
    builder.add(BadAbstractClassNameCheck.class);
    builder.add(BadTypeParameterNameCheck.class);
    builder.add(BadPackageNameCheck.class);
    builder.add(MissingCurlyBracesCheck.class);
    builder.add(TooManyStatementsPerLineCheck.class);
    builder.add(LeftCurlyBraceStartLineCheck.class);
    builder.add(RightCurlyBraceSameLineAsNextBlockCheck.class);
    builder.add(RightCurlyBraceStartLineCheck.class);
    builder.add(RightCurlyBraceDifferentLineAsNextBlockCheck.class);
    builder.add(LeftCurlyBraceEndLineCheck.class);
    builder.add(UselessParenthesesCheck.class);
    builder.add(ObjectFinalizeCheck.class);
    builder.add(ObjectFinalizeOverridenCheck.class);
    builder.add(ObjectFinalizeOverridenCallsSuperFinalizeCheck.class);
    builder.add(ClassVariableVisibilityCheck.class);
    builder.add(ForLoopCounterChangedCheck.class);
    builder.add(LabelsShouldNotBeUsedCheck.class);
    builder.add(SwitchLastCaseIsDefaultCheck.class);
    builder.add(EmptyStatementUsageCheck.class);
    builder.add(ModifiersOrderCheck.class);
    builder.add(AssignmentInSubExpressionCheck.class);
    builder.add(TrailingCommentCheck.class);
    builder.add(UselessImportCheck.class);
    builder.add(MissingDeprecatedCheck.class);
    builder.add(IndentationCheck.class);
    builder.add(HiddenFieldCheck.class);
    builder.add(DeprecatedTagPresenceCheck.class);
    builder.add(FixmeTagPresenceCheck.class);
    builder.add(TodoTagPresenceCheck.class);
    builder.add(UtilityClassWithPublicConstructorCheck.class);
    builder.add(StringLiteralInsideEqualsCheck.class);
    builder.add(ReturnOfBooleanExpressionsCheck.class);
    builder.add(BooleanLiteralCheck.class);
    builder.add(ExpressionComplexityCheck.class);
    builder.add(NestedTryCatchCheck.class);
    builder.add(SystemExitCalledCheck.class);
    builder.add(ReturnInFinallyCheck.class);
    builder.add(IfConditionAlwaysTrueOrFalseCheck.class);
    builder.add(CaseInsensitiveComparisonCheck.class);
    builder.add(MethodWithExcessiveReturnsCheck.class);
    builder.add(CollectionIsEmptyCheck.class);
    builder.add(SynchronizedClassUsageCheck.class);
    builder.add(NonStaticClassInitializerCheck.class);
    builder.add(ReturnEmptyArrayNotNullCheck.class);
    builder.add(ConstantsShouldBeStaticFinalCheck.class);
    builder.add(ThrowsFromFinallyCheck.class);
    builder.add(SystemOutOrErrUsageCheck.class);
    builder.add(ExceptionsShouldBeImmutableCheck.class);
    builder.add(CollapsibleIfCandidateCheck.class);
    builder.add(NestedIfStatementsCheck.class);
    builder.add(CatchOfThrowableOrErrorCheck.class);
    builder.add(ImplementsEnumerationCheck.class);
    builder.add(CloneMethodCallsSuperCloneCheck.class);
    builder.add(SwitchCaseTooBigCheck.class);
    builder.add(SwitchCaseWithoutBreakCheck.class);
    builder.add(CatchUsesExceptionWithContextCheck.class);
    builder.add(MethodTooBigCheck.class);
    builder.add(KeywordAsIdentifierCheck.class);
    builder.add(AnonymousClassesTooBigCheck.class);
    builder.add(SunPackagesUsedCheck.class);
    builder.add(SeveralBreakOrContinuePerLoopCheck.class);
    builder.add(EmptyMethodsCheck.class);
    builder.add(MethodOnlyCallsSuperCheck.class);
    builder.add(ObjectFinalizeOverridenNotPublicCheck.class);
    builder.add(ObjectFinalizeOverloadedCheck.class);
    builder.add(ConcatenationWithStringValueOfCheck.class);
    builder.add(PrintStackTraceCalledWithoutArgumentCheck.class);
    builder.add(ArrayDesignatorAfterTypeCheck.class);
    builder.add(ErrorClassExtendedCheck.class);
    builder.add(InstanceofUsedOnExceptionCheck.class);
    builder.add(StringLiteralDuplicatedCheck.class);
    builder.add(ToStringUsingBoxingCheck.class);
    builder.add(GarbageCollectorCalledCheck.class);
    builder.add(ArrayDesignatorOnVariableCheck.class);
    builder.add(DefaultPackageCheck.class);
    builder.add(MethodNamedHashcodeOrEqualCheck.class);
    builder.add(NestedBlocksCheck.class);
    builder.add(InterfaceAsConstantContainerCheck.class);
    builder.add(MethodNamedEqualsCheck.class);
    builder.add(EqualsNotOverridenWithCompareToCheck.class);
    builder.add(EqualsOverridenWithHashCodeCheck.class);
    builder.add(SwitchWithLabelsCheck.class);
    builder.add(SwitchAtLeastThreeCasesCheck.class);
    builder.add(ClassCouplingCheck.class);
    builder.add(OctalValuesCheck.class);
    builder.add(NoPmdTagPresenceCheck.class);
    builder.add(NoCheckstyleTagPresenceCheck.class);
    builder.add(ParameterReassignedToCheck.class);
    builder.add(HardcodedIpCheck.class);
    builder.add(HardcodedURICheck.class);
    builder.add(LoggersDeclarationCheck.class);
    builder.add(MethodNameSameAsClassCheck.class);
    builder.add(CollectionImplementationReferencedCheck.class);
    builder.add(IncorrectOrderOfMembersCheck.class);
    builder.add(PublicStaticFieldShouldBeFinalCheck.class);
    builder.add(WildcardReturnParameterTypeCheck.class);
    builder.add(UnusedLocalVariableCheck.class);
    builder.add(UnusedPrivateFieldCheck.class);
    builder.add(StringBufferAndBuilderWithCharCheck.class);
    builder.add(FileHeaderCheck.class);
    builder.add(IncrementDecrementInSubExpressionCheck.class);
    builder.add(CollectionsEmptyConstantsCheck.class);
    builder.add(UselessExtendsCheck.class);
    builder.add(DITCheck.class);
    builder.add(ArchitectureCheck.class);
    builder.add(CallToDeprecatedMethodCheck.class);
    builder.add(CallToFileDeleteOnExitMethodCheck.class);
    builder.add(UnusedPrivateMethodCheck.class);
    builder.add(RedundantThrowsDeclarationCheck.class);
    builder.add(ThrowsSeveralCheckedExceptionCheck.class);
    builder.add(ThreadRunCheck.class);
    builder.add(DuplicateConditionIfElseIfCheck.class);
    builder.add(ImmediatelyReturnedVariableCheck.class);
    builder.add(LambdaSingleExpressionCheck.class);
    builder.add(LambdaOptionalParenthesisCheck.class);
    builder.add(AnonymousClassShouldBeLambdaCheck.class);
    builder.add(AbstractClassNoFieldShouldBeInterfaceCheck.class);
    builder.add(SAMAnnotatedCheck.class);
    builder.add(CatchNPECheck.class);
    builder.add(FieldNameMatchingTypeNameCheck.class);
    builder.add(AbstractClassWithoutAbstractMethodCheck.class);
    builder.add(UnusedMethodParameterCheck.class);
    builder.add(MagicNumberCheck.class);
    builder.add(StringConcatenationInLoopCheck.class);
    builder.add(CompareObjectWithEqualsCheck.class);
    builder.add(RepeatAnnotationCheck.class);
    builder.add(NPEThrowCheck.class);
    builder.add(NullDereferenceInConditionalCheck.class);
    builder.add(SelfAssignementCheck.class);
    builder.add(MismatchPackageDirectoryCheck.class);
    builder.add(ReplaceLambdaByMethodRefCheck.class);
    builder.add(FieldModifierCheck.class);
    builder.add(SerializableFieldInSerializableClassCheck.class);
    builder.add(PackageInfoCheck.class);
    builder.add(SwitchWithTooManyCasesCheck.class);
    builder.add(IdenticalCasesInSwitchCheck.class);
    builder.add(IdenticalOperandOnBinaryExpressionCheck.class);
    builder.add(FloatEqualityCheck.class);
    builder.add(SQLInjectionCheck.class);
    builder.add(TernaryOperatorCheck.class);
    builder.add(OverrideAnnotationCheck.class);
    builder.add(ForLoopIncrementAndUpdateCheck.class);
    builder.add(EmptyClassCheck.class);
    builder.add(InstanceOfAlwaysTrueCheck.class);
    builder.add(RedundantTypeCastCheck.class);
    builder.add(CollectionCallingItselfCheck.class);
    builder.add(UnusedLabelCheck.class);
    builder.add(ThrowCheckedExceptionCheck.class);
    builder.add(CastArithmeticOperandCheck.class);
    builder.add(IgnoredReturnValueCheck.class);
    builder.add(ToStringReturningNullCheck.class);
    builder.add(TransactionalMethodVisibilityCheck.class);
    builder.add(CompareToResultTestCheck.class);
    builder.add(SecureCookieCheck.class);
    builder.add(CatchIllegalMonitorStateExceptionCheck.class);
    builder.add(ForLoopTerminationConditionCheck.class);
    builder.add(HttpRefererCheck.class);
    builder.add(HardCodedCredentialsCheck.class);
    builder.add(PseudoRandomCheck.class);
    builder.add(MainMethodThrowsExceptionCheck.class);
    builder.add(ResultSetIsLastCheck.class);
    builder.add(HasNextCallingNextCheck.class);
    builder.add(ThreadWaitCallCheck.class);
    builder.add(WaitOnConditionCheck.class);
    builder.add(DisallowedMethodCheck.class);
    builder.add(ForLoopIncrementSignCheck.class);
    builder.add(ForLoopFalseConditionCheck.class);
    builder.add(DeprecatedHashAlgorithmCheck.class);
    builder.add(NullCipherCheck.class);
    builder.add(GetRequestedSessionIdCheck.class);
    builder.add(ConcurrentLinkedQueueSizeCheck.class);
    builder.add(ServletInstanceFieldCheck.class);
    builder.add(BigDecimalDoubleConstructorCheck.class);
    builder.add(ReflectionOnNonRuntimeAnnotationCheck.class);
    builder.add(WaitInSynchronizeCheck.class);
    builder.add(ThreadSleepCheck.class);
    builder.add(WaitInWhileLoopCheck.class);
    builder.add(IteratorNextExceptionCheck.class);
    builder.add(AvoidDESCheck.class);
    builder.add(RSAUsesOAEPCheck.class);
    builder.add(ConstructorCallingOverridableCheck.class);
    builder.add(EqualsOnAtomicClassCheck.class);
    builder.add(LDAPInjectionCheck.class);
    builder.add(NonShortCircuitLogicCheck.class);
    builder.add(OSCommandInjectionCheck.class);
    builder.add(ArrayHashCodeAndToStringCheck.class);
    builder.add(DefaultEncodingUsageCheck.class);
    builder.add(CloneableImplementingCloneCheck.class);
    builder.add(PrintfCheck.class);
    builder.add(ModulusEqualityCheck.class);
    builder.add(RunFinalizersCheck.class);
    builder.add(LongBitsToDoubleOnIntCheck.class);
    builder.add(SynchronizationOnStringOrBoxedCheck.class);
    builder.add(SerializableSuperConstructorCheck.class);
    builder.add(NonSerializableWriteCheck.class);
    builder.add(InnerClassOfSerializableCheck.class);
    builder.add(InnerClassOfNonSerializableCheck.class);
    builder.add(SerialVersionUidCheck.class);
    builder.add(SerializableComparatorCheck.class);
    builder.add(TransientFieldInNonSerializableCheck.class);
    builder.add(CustomSerializationMethodCheck.class);
    builder.add(InterfaceOrSuperclassShadowingCheck.class);
    builder.add(RedundantModifierCheck.class);
    builder.add(MathOnFloatCheck.class);
    builder.add(StringToPrimitiveConversionCheck.class);
    builder.add(ClassNamedLikeExceptionCheck.class);
    builder.add(ProtectedMemberInFinalClassCheck.class);
    builder.add(SuppressWarningsCheck.class);
    builder.add(ImmediateReverseBoxingCheck.class);
    builder.add(CustomCryptographicAlgorithmCheck.class);
    builder.add(UnusedTypeParameterCheck.class);
    builder.add(ShiftOnIntOrLongCheck.class);
    builder.add(CompareToReturnValueCheck.class);
    builder.add(FinalizeFieldsSetCheck.class);
    builder.add(UnnecessarySemicolonCheck.class);
    builder.add(NotifyCheck.class);
    builder.add(ScheduledThreadPoolExecutorZeroCheck.class);
    builder.add(ThreadOverridesRunCheck.class);
    builder.add(CollectionInappropriateCallsCheck.class);
    builder.add(BooleanMethodReturnCheck.class);
    builder.add(PrimitiveTypeBoxingWithToStringCheck.class);
    builder.add(SillyBitOperationCheck.class);
    builder.add(InvalidDateValuesCheck.class);
    builder.add(EqualsNotOverriddenInSubclassCheck.class);
    builder.add(ClassComparedByNameCheck.class);
    builder.add(ClassWithOnlyStaticMethodsInstantiationCheck.class);
    builder.add(SerializableObjectInSessionCheck.class);
    builder.add(StaticFieldInitializationCheck.class);
    builder.add(UselessIncrementCheck.class);
    builder.add(ObjectCreatedOnlyToCallGetClassCheck.class);
    builder.add(PrimitiveWrappersInTernaryOperatorCheck.class);
    builder.add(SynchronizedLockCheck.class);
    builder.add(SymmetricEqualsCheck.class);
    builder.add(CallSuperMethodFromInnerClassCheck.class);
    builder.add(SelectorMethodArgumentCheck.class);
    builder.add(ThreadAsRunnableArgumentCheck.class);
    builder.add(SynchronizedFieldAssignmentCheck.class);
    builder.add(NullDereferenceCheck.class);
    builder.add(ConditionAlwaysTrueOrFalseCheck.class);
    builder.add(UnclosedResourcesCheck.class);
    builder.add(CustomUnclosedResourcesCheck.class);
    builder.add(StaticFieldUpateCheck.class);
    builder.add(IgnoredStreamReturnValueCheck.class);
    builder.add(DateUtilsTruncateCheck.class);
    builder.add(PreparedStatementAndResultSetCheck.class);
    builder.add(URLHashCodeAndEqualsCheck.class);
    builder.add(ChildClassShadowFieldCheck.class);
    builder.add(OperatorPrecedenceCheck.class);
    builder.add(NestedEnumStaticCheck.class);
    builder.add(UnusedReturnedDataCheck.class);
    builder.add(StringToStringCheck.class);
    builder.add(ThreadStartedInConstructorCheck.class);
    builder.add(KeySetInsteadOfEntrySetCheck.class);
    builder.add(IndexOfWithPositiveNumberCheck.class);
    builder.add(ReadObjectSynchronizedCheck.class);
    builder.add(AbsOnNegativeCheck.class);
    builder.add(StaticMultithreadedUnsafeFieldsCheck.class);
    builder.add(LocksNotUnlockedCheck.class);
    builder.add(EqualsArgumentTypeCheck.class);
    builder.add(ConstantMathCheck.class);
    builder.add(SillyEqualsCheck.class);
    builder.add(IndexOfStartPositionCheck.class);
    builder.add(StaticMembersAccessCheck.class);
    builder.add(MutableMembersUsageCheck.class);
    builder.add(StaticMethodCheck.class);
    builder.add(ForLoopUsedAsWhileLoopCheck.class);
    builder.add(MultilineBlocksCurlyBracesCheck.class);
    builder.add(EnumMapCheck.class);
    builder.add(FileCreateTempFileCheck.class);
    builder.add(BooleanInversionCheck.class);
    builder.add(InnerStaticClassesCheck.class);
    builder.add(StandardFunctionalInterfaceCheck.class);
    builder.add(WildcardImportsShouldNotBeUsedCheck.class);
    builder.add(FinalClassCheck.class);
    builder.add(OneDeclarationPerLineCheck.class);
    builder.add(ServletMethodsExceptionsThrownCheck.class);
    builder.add(DynamicClassLoadCheck.class);
    builder.add(MembersDifferOnlyByCapitalizationCheck.class);
    builder.add(LoopsOnSameSetCheck.class);
    builder.add(PublicStaticMutableMembersCheck.class);
    builder.add(OneClassInterfacePerFileCheck.class);
    builder.add(CloneOverrideCheck.class);
    builder.add(TooManyMethodsCheck.class);
    builder.add(UppercaseSuffixesCheck.class);
    builder.add(InnerClassTooManyLinesCheck.class);
    builder.add(DefaultInitializedFieldCheck.class);
    builder.add(EscapedUnicodeCharactersCheck.class);
    builder.add(MainInServletCheck.class);
    builder.add(AtLeastOneConstructorCheck.class);
    builder.add(CatchExceptionCheck.class);
    builder.add(VariableDeclarationScopeCheck.class);
    builder.add(AnnotationArgumentOrderCheck.class);
    builder.add(DeadStoreCheck.class);
    builder.add(DataStoredInSessionCheck.class);
    builder.add(DiamondOperatorCheck.class);
    builder.add(CommentRegularExpressionCheck.class);
    builder.add(AssertOnBooleanVariableCheck.class);
    builder.add(CombineCatchCheck.class);
    builder.add(TryWithResourcesCheck.class);
    builder.add(ConstantMethodCheck.class);
    builder.add(ChangeMethodContractCheck.class);
    builder.add(CatchRethrowingCheck.class);
    builder.add(InappropriateRegexpCheck.class);
    builder.add(CallOuterPrivateMethodCheck.class);
    builder.add(InterruptedExceptionCheck.class);
    builder.add(RawByteBitwiseOperationsCheck.class);
    builder.add(EnumSetCheck.class);
    builder.add(StringPrimitiveConstructorCheck.class);
    builder.add(EnumMutableFieldCheck.class);
    builder.add(StringMethodsWithLocaleCheck.class);
    builder.add(StringMethodsOnSingleCharCheck.class);
    builder.add(ConfusingOverloadCheck.class);
    builder.add(RedundantAbstractMethodCheck.class);
    builder.add(NonNullSetToNullCheck.class);
    builder.add(ConstructorInjectionCheck.class);
    builder.add(NoWayOutLoopCheck.class);
    builder.add(ExternalizableClassConstructorCheck.class);
    builder.add(PrivateReadResolveCheck.class);
    builder.add(RandomFloatToIntCheck.class);
    builder.add(CognitiveComplexityMethodCheck.class);
    builder.add(SyncGetterAndSetterCheck.class);
    builder.add(ToArrayCheck.class);
    builder.add(ClassWithoutHashCodeInHashStructureCheck.class);
    builder.add(IgnoredOperationStatusCheck.class);
    builder.add(UnderscoreOnNumberCheck.class);
    builder.add(OptionalAsParameterCheck.class);
    builder.add(DoubleBraceInitializationCheck.class);
    builder.add(ArraysAsListOfPrimitiveToStreamCheck.class);
    builder.add(DivisionByZeroCheck.class);
    builder.add(SimpleClassNameCheck.class);
    builder.add(NullShouldNotBeUsedWithOptionalCheck.class);
    builder.add(PrivateFieldUsedLocallyCheck.class);
    builder.add(OptionalGetBeforeIsPresentCheck.class);
    builder.add(ValueBasedObjectsShouldNotBeSerializedCheck.class);
    builder.add(FilesExistsJDK8Check.class);
    builder.add(StaticImportCountCheck.class);
    builder.add(ClassFieldCountCheck.class);
    builder.add(DoubleCheckedLockingCheck.class);
    builder.add(WriteObjectTheOnlySynchronizedMethodCheck.class);
    builder.add(TwoLocksWaitCheck.class);
    builder.add(SynchronizationOnGetClassCheck.class);
    builder.add(DisallowedClassCheck.class);
    builder.add(LazyArgEvaluationCheck.class);
    builder.add(BooleanMethodNameCheck.class);
    builder.add(StaticFieldUpdateInConstructorCheck.class);
    return Collections.unmodifiableList(builder);
  }

  public static List<Class<? extends JavaCheck>> getJavaTestChecks() {
    List<Class<? extends JavaCheck>> builder = new ArrayList<>();
    builder.add(IgnoredTestsCheck.class);
    builder.add(BooleanLiteralInAssertionsCheck.class);
    builder.add(AssertionsWithoutMessageCheck.class);
    builder.add(CallSuperInTestCaseCheck.class);
    builder.add(AssertionInThreadRunCheck.class);
    builder.add(NoTestInTestClassCheck.class);
    builder.add(AssertionsInTestsCheck.class);
    builder.add(JunitMethodDeclarationCheck.class);
    builder.add(AssertionsCompletenessCheck.class);
    builder.add(ThreadSleepInTestsCheck.class);
    builder.add(UnusedTestRuleCheck.class);
    builder.add(BadTestClassNameCheck.class);
    builder.add(BadTestMethodNameCheck.class);
    builder.add(AssertionFailInCatchBlockCheck.class);
    return Collections.unmodifiableList(builder);
  }

  public static List<Class<? extends JavaCheck>> getXmlChecks() {
    List<Class<? extends JavaCheck>> builder = new ArrayList<>();
    builder.addAll(getMavenChecks());
    builder.add(DefaultInterceptorsLocationCheck.class);
    builder.add(InterceptorExclusionsCheck.class);
    builder.add(SingleConnectionFactoryCheck.class);
    builder.add(SecurityConstraintsInWebXmlCheck.class);
    builder.add(ValidationFiltersCheck.class);
    builder.add(ActionNumberCheck.class);
    builder.add(FormNameDuplicationCheck.class);
    return Collections.unmodifiableList(builder);
  }

  private static List<Class<? extends JavaCheck>> getMavenChecks() {
    List<Class<? extends JavaCheck>> builder = new ArrayList<>();
    builder.add(PomElementOrderCheck.class);
    builder.add(DependencyWithSystemScopeCheck.class);
    builder.add(GroupIdNamingConventionCheck.class);
    builder.add(ArtifactIdNamingConventionCheck.class);
    builder.add(DisallowedDependenciesCheck.class);
    builder.add(DeprecatedPomPropertiesCheck.class);
    return Collections.unmodifiableList(builder);

  }
}
