/*
 * SonarQube Java
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package com.sonar.it.java.suite;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

final class AnalysisFixtures {

  record Fixture(String name, String description, Path project, String sourceRoot, List<String> expectedFiles,
                 List<String> sourcePaths, String profile, Map<String, String> properties, int expectedProbes,
                 Boolean expectCompilerSuccess) { }

  private AnalysisFixtures() { }

  static Fixture clean(Path project, boolean expectResolved, boolean compilation) throws IOException {
    String root = "src/main/java";
    write(project, root + "/bindings/BindingFixture.java", consumer(false, false));
    writeDependencies(project, root);
    String profile = expectResolved ? "semantic-bindings-clean-sourcepaths" : "semantic-bindings-clean-unresolved";
    if (compilation) {
      profile = "semantic-bindings-clean-bytecode";
    }
    return new Fixture("Clean compilation", "Three JDK-only files analyzed separately; exact overload and inherited-field bindings; generated bytecode checked during analysis.",
      project, root, List.of(root + "/bindings/BindingFixture.java", root + "/bindings/BindingHelper.java", root + "/bindings/BindingParent.java"),
      List.of(root), profile, Map.of("sonar.java.fileByFile", "true"), 4, true);
  }

  static Fixture dependency(Path project, boolean sourcePaths) throws IOException {
    String consumerRoot = "consumer/src/main/java";
    String dependencyRoot = "dependency/src/main/java";
    write(project, consumerRoot + "/bindings/BindingFixture.java", consumer(true, false));
    writeDependencies(project, dependencyRoot);
    return new Fixture("Dependency outside analysis", "Only the consumer is indexed; dependency source roots resolve project bindings without analyzing dependency files; MissingType stays unknown.",
      project, consumerRoot, List.of(consumerRoot + "/bindings/BindingFixture.java"), List.of(consumerRoot, dependencyRoot),
      sourcePaths ? "semantic-bindings" : "semantic-bindings-unresolved", Map.of(), 5, false);
  }

  static Fixture fallback(Path project) throws IOException {
    String root = "bindings";
    write(project, root + "/BindingFixture.java", consumer(true, true));
    write(project, root + "/BindingHelper.java", """
      package bindings;
      class BindingHelper {
        String select(String value) { return value; }
        int select(int value) { return value; }
      }
      class BindingParent { protected int inheritedValue; }
      """);
    return new Fixture("Compilation failure recovery", "A missing type causes compiler failure; batch analysis still resolves project bindings and visits both files.",
      project, root, List.of(root + "/BindingFixture.java", root + "/BindingHelper.java"), List.of("."),
      "semantic-bindings-fallback", Map.of(), 5, false);
  }

  private static String consumer(boolean missingType, boolean syntaxFinding) {
    return """
      package bindings;
      class BindingFixture extends BindingParent {
        void check() {
          String text = "x";
          BindingHelper helper = new BindingHelper();
          int fieldValue = inheritedValue;
          String result = helper.select(text);
      %s
      %s
        }
      }
      """.formatted(missingType ? "    MissingType missing = null;" : "", syntaxFinding ? "    ;" : "");
  }

  private static void writeDependencies(Path project, String root) throws IOException {
    write(project, root + "/bindings/BindingHelper.java", """
      package bindings;
      public class BindingHelper {
        public String select(String value) { return value; }
        public int select(int value) { return value; }
      }
      """);
    write(project, root + "/bindings/BindingParent.java", "package bindings; public class BindingParent { protected int inheritedValue; }");
  }

  private static void write(Path project, String file, String content) throws IOException {
    Path target = project.resolve(file);
    Files.createDirectories(target.getParent());
    Files.writeString(target, content);
  }
}
