name: 'Close stale PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: sonar-xs-public
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. If there is no activity in the next 7 days it will be closed automatically'
          stale-pr-label: 'stale'
          days-before-stale: 7
          days-before-close: 7
          exempt-pr-labels: 'do-not-close,External Contribution'
