name: nightly build
# This workflow is triggered on schedule
on:
  schedule:
    - cron:  '0 1 * * *'   

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: Nightly build action      

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    name: Run a nightly build
    steps:
    - name: starts a build    
      env:
        CIRRUS_TOKEN: ${{ secrets.CIRRUS_TOKEN }}
      uses: SonarSource/gh-action_nightly_build@master
      with:
        branch: 'master'
    #slack notifications
    - name: Notify success on Slack
      uses: Ilshidur/action-slack@1.6.2
      env:
        SLACK_OVERRIDE_MESSAGE: 'Nightly build successful'
      with:
        args: 'Succeed to build dogfood branch'
    - name: Notify failures on Slack
      uses: Ilshidur/action-slack@1.6.2
      if: failure()
      env:
        SLACK_OVERRIDE_MESSAGE: 'Nightly build: *failed*, see the logs at https://github.com/SonarSource/sonar-java/actions'
      with:
        args: 'Fail to build dogfood branch'