name: Prepare Next Development Iteration

on:
  workflow_dispatch:
 
jobs:
  Next-Iteration-Job:
    name: Next Iteration Job
    runs-on: github-ubuntu-latest-s
    permissions:
      statuses: read
      id-token: write
      contents: write
      actions: write
      pull-requests: write

    steps:
      - name: Test
        uses: SonarSource/release-github-actions/update-analyzer@tt/GHA-200_update_plugin
        with:
          release-version: "8.30.0.9999"
          ticket-key: "SONAR-9999999999"
          secret-name: sonar-java-release-automation
          plugin-name: "java"
          # plugin-suffix: ""
          plugin-artifacts: "java"
          draft: true
          reviewers: tomasz-tylenda-sonarsource
          base-branch: master

