---
name: sonar-release
# This workflow is triggered by automated-release.yml
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v7
    with:
      publishToBinaries: true
      mavenCentralSync: true
      slackChannel: squad-corelang-releases
      version: ${{ inputs.version }}
      dryRun: ${{ inputs.dryRun == true }}
