name: Unified Dogfooding scans
on:
  schedule:
    - cron: "0 4 * * 1-5" # Run the workflow Mon-Fri at 04:00 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: sonar-l-public
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.7.7
      - uses: SonarSource/ci-github-actions/build-maven@v1
        env:
          MAVEN_OPTS: "-Xmx8g"
          JAVA_TOOL_OPTIONS: ""
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          scanner-java-opts: '-Xmx2g'
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: org.sonarsource.java:java
          primary_platform: "Next"
          shadow1_project_key: org.sonarsource.java:java
          shadow1_platform: "SQC-EU"
          shadow2_project_key: org.sonarsource.java:java
          shadow2_platform: "SQC-US"
