name: Update Rule Metadata

on: workflow_dispatch

jobs:
  rule-metadata-update:
    runs-on: github-ubuntu-latest-m
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Update Rule Metadata
        id: update-rule-metadata
        uses: SonarSource/release-github-actions/update-rule-metadata@v1
        with:
          labels: ''
          rspec-token-suffix: 'rspec'
          post-update: |
            sed --in-place='' -e 's/rule:java:S3649/rule:javasecurity:S3649/g' 'sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2077.html'

      - name: Check Rule Metadata Changes
        run: |
          if [ "${{ steps.update-rule-metadata.outputs.has-changes }}" == "true" ]; then
            echo "::notice title=Rule Metadata Changes::Changes detected and PR created: ${{ steps.update-rule-metadata.outputs.pull-request-url }}"
          else
            echo "::notice title=Rule Metadata Status::No changes to the rules metadata were detected"
          fi