name: "Validate commit message before merge"
on:
  push:
    branches:
      - "alban/validate-commit-message"
#  merge_group:
#    branches:
#      - main
jobs:
    validate-commit-message:
        runs-on: ubuntu-latest
        steps:
          - name: Logging
            run: |
              echo "${{toJSON(github.event)}}"
