name: "Validate commit message before merge"
on:
  push:
    branches:
      - "alban/validate-commit-message"
#  merge_group:
#    branches:
#      - main
  merge_group:
    paths-ignore:
      - '.github/workflows/*.yml'
jobs:
    validate-commit-message:
        runs-on: ubuntu-latest
        if: ! ( startsWith('SONARJAVA-', github.event.head_commit.message) || startsWith('[maintenance]', github.event.head_commit.message)
        steps:
          - name: Validate commit message before merge
            run: |
              echo "${{toJSON(github.event)}}" && false
